# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-DynDNS
version:      0.93
version_from: lib/Net/DNS/DynDNS.pm
installdirs:  site
requires:
    HTTP::Cookies:                 0
    HTTP::Headers:                 0
    LWP:                           0
    Net::HTTPS:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
