--- #YAML:1.0
name:               Net-DNS-DynDNS
version:            0.98
abstract:           Update dyndns.org with correct ip address for your domain name
author:
    - David Dick <ddick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    Crypt::SSLeay:  0
    English:        0
    HTTP::Cookies:  0
    HTTP::Headers:  0
    LWP:            0
    Net::HTTPS:     0
    perl:           5.010000
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
